### ISSUE TITLE
Fatal error: Interface 'Symfony\Component\HttpKernel\TerminableInterface' not fo und

### ISSUE THREAD

**Issue by verglas** [sseffa/fullycms#22]
Fatal error: Interface 'Symfony\Component\HttpKernel\TerminableInterface' not fo
und in fullycms-master\vendor\laravel\framework\src\Illumin
ate\Foundation\Application.php on line 24

I tried two methods

1，download fullycms-master.zip, uzip.
2，php composer.phar update or php composer.phar install
3，fatal error.

1，php composer.phar create-project sseffa/sf_cms --prefer-dist
2，Could not find package sseffa/sf_cms with stability stable.

ps: The composer was wall(GFW),I use the VPN in South Korea

**Comment by HannonTN** [comment]
yes, i'm getting the same error as verglas.
