### ISSUE TITLE
Fatal error: require(): Failed opening required '../bootstrap/../vendor/autoload.php

### ISSUE THREAD

**Issue by LaravelNick** [sseffa/fullycms#26]
Hi Sefa,

You're doing an excellent job with this CMS and thanks for converting it to Laravel 5.

However, I did get the error message mentioned above whilst trying to install this version.

Many thanks and keep up the good work ;-)

**Comment by sseffa** [comment]
run "composer install" in your root project folder

**Comment by LaravelNick** [comment]
I did that and it all went through fine.

The error occurred on step 4.

4. Run php artisan app:install to setup and seed your database.

**Comment by sseffa** [comment]
1) open in the folder, run "composer install"

2) create database

3) Enter your database details into config/database.php

4) Run php artisan app:install to setup and seed your database.

**Comment by LaravelNick** [comment]
Thanks for that.
