### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'

### ISSUE THREAD

**Issue by birkansava** [sseffa/fullycms#28]
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags' neden veriyor anlamadım ? (sadece frontend bölümünde)

**Comment by birkansava** [comment]
cache false yapınca düzeliyor ama true olduğu zaman hatanın sebebi ne

**Comment by sseffa** [comment]
hatanın kaynağı file ve array cache tipinde tags fonksiyonu yok 4.2 sürümünde çözmüştüm fakat burda tekrar hata oldu sanırım ama redis, memcache ya da apc cache kullanırsan bu hata gözükmüyor, birkaç hafta içinde düzeltirim ama sorunu
