### ISSUE TITLE
install by composer error

### ISSUE THREAD

**Issue by Naser-SherafatiNia** [sseffa/fullycms#29]
I try install fullycms by composer
"composer create-project sseffa/fullycms --prefer-dist"

and i'm getting error
"Could not find package sseffa/fullycms with stability stable."

**Comment by sseffa** [comment]
https://github.com/sseffa/fullycms#installation

**Comment by valle6** [comment]
The link says the same:  composer create-project sseffa/fullycms --prefer-dist

**Comment by Wmas** [comment]
Hello there,
I had the same problem.
Just download the zip file, unzip the file and upload it to your server.
From here follow then the other steps and you will be ready to go.
I hope this will help.
As sseffa say this is still buggy and not a stable version but you can get an idea of it.
