### ISSUE TITLE
git clone git@github.com:sseffa/fullycms.git

### ISSUE THREAD

**Issue by ayalaarevalo** [sseffa/fullycms#30]
aayala@aayala-Aspire-M3970:~/Code$ git clone git@github.com:sseffa/fullycms.git
Clonar en «fullycms»...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

aayala@aayala-Aspire-M3970:~/Code$ composer create-project sseffa/fullycms --prefer-dist

                                                                 
  [InvalidArgumentException]                                     
  Could not find package sseffa/fullycms with stability stable.  
                                                                 

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

**Comment by RudolfFussek** [comment]
I have the same...

**Comment by ntc113** [comment]
i have the same error
