### ISSUE TITLE
Great dev package

### ISSUE THREAD

**Issue by phillipmadsen** [sseffa/fullycms#39]
I  love playing around with the package you have created. But I  cannot find a good tutorial on Sentinel and i am having issues getting a working registration up and running. do you have on in dev or any info on how I  can achieve this?

**Comment by phillipmadsen** [comment]
One more question also. I  have packages im using that conflict with illuminate/html  such as "laravelcollective/html": "5.1.x-dev", do you have a way to use both or can I  replace yours with the collective one that is more widely used?

**Comment by sseffa** [comment]
setting a registration in sentinel, i have written a code like that : https://github.com/sseffa/fullycms/blob/master/app/Console/Commands/AppCommand.php#L226  

and you can change my package with the ones that is widely used

**Comment by phillipmadsen** [comment]
Thank you for the command. I  was looking for more of a registration for the AuthController@getRegister or something that I  can use on a register new user form. I  am working on it as we speak. Your command seems to be something I  can use but I  need to look into it. I  was hoping you might have one already created for a  registration form like the one you have for the login form. If you can direct me to the Sentinel Source you created your login from I  would appreciate it.

**Comment by sseffa** [comment]
this is the url of sentinel package's own document's https://cartalyst.com/manual/sentinel/2.0
