### ISSUE TITLE
Created Fonksiyonu

### ISSUE THREAD

**Issue by zahideroglu** [sseffa/fullycms#41]
FatalErrorException in NewsController.php line 70:
Call to undefined method Fully\Repositories\News\CacheDecorator::create()

Admin üzerinden eklediğim veya güncellediğim her hangi bir veri de  newcontroller den hata alıyorum. Created fonksiyonunu çağıramıyor galiba yardımcı olursanız sevinirim. Teşekkür ederim

**Comment by sseffa** [comment]
son commit ile bu ve birkaç hatayı düzelttim
